--Por Arthur, Carlos Eduardo, Heitor e Jhonathan

INSERT INTO Movimentos (Nome, PP, Acerto, Poder, Tipo, Descricao)
VALUES
('Thunder Shock', 30, 100, 40, 'Electric', 'Um choque elétrico fraco ataca o oponente.'),
('Flamethrower', 15, 100, 90, 'Fire', 'Um ataque de chama poderosa que pode causar queimaduras.'),
('Hydro Pump', 5, 80, 110, 'Water', 'Dispara um jato de água de alta pressão contra o alvo.'),
('Solar Beam', 10, 100, 120, 'Grass', 'Absorve luz solar no primeiro turno e dispara no segundo.'),
('Quick Attack', 30, 100, 40, 'Normal', 'Um ataque rápido que sempre atinge primeiro.'),
('Hyper Beam', 5, 90, 150, 'Normal', 'Um ataque devastador, o usuário precisa recarregar no próximo turno.'),
('Ice Beam', 10, 100, 90, 'Ice', 'Dispara um raio de gelo que pode congelar o alvo.'),
('Psychic', 10, 100, 90, 'Psychic', 'Lança uma onda psíquica para atacar o oponente.'),
('Shadow Ball', 15, 100, 80, 'Ghost', 'Lança uma bola de sombra para diminuir a defesa especial do oponente.'),
('Rock Slide', 10, 90, 75, 'Rock', 'Lança pedras no oponente, com chance de fazer flinchar.'),
('Iron Tail', 15, 75, 100, 'Steel', 'Ataca o oponente com uma cauda de aço.'),
('Dragon Claw', 15, 100, 80, 'Dragon', 'Ataca o alvo com garras afiadas.'),
('Earthquake', 10, 100, 100, 'Ground', 'Causa um terremoto que atinge todos os Pokémon no campo.'),
('Sludge Bomb', 10, 100, 90, 'Poison', 'Lança uma bomba tóxica que pode envenenar o alvo.'),
('Thunderbolt', 15, 100, 90, 'Electric', 'Ataca com um relâmpago poderoso. Pode paralisar o alvo.'),
('Surf', 15, 100, 90, 'Water', 'Invoca uma onda para atacar o oponente.'),
('Confuse Ray', 10, NULL, NULL, 'Ghost', 'Lança um raio que confunde o oponente.'),
('Will-O-Wisp', 15, 85, NULL, 'Fire', 'Invoca chamas espectrais que causam queimadura.'),
('Fly', 15, 95, 90, 'Flying', 'O Pokémon voa no primeiro turno e ataca no segundo.'),
('Bite', 25, 100, 60, 'Dark', 'Morde o alvo, podendo causar flinch.'),
('Stun Spore', 30, 75, NULL, 'Grass', 'Libera esporos que paralisam o oponente.'),
('Leech Seed', 10, 90, NULL, 'Grass', 'Planta uma semente que drena vida do oponente a cada turno.'),
('Gust', 35, 100, 40, 'Flying', 'Um golpe de vento que atinge o oponente.'),
('Dynamic Punch', 5, 50, 100, 'Fighting', 'Um soco forte que sempre causa confusão.'),
('Tackle', 35, 95, 40, 'Normal', 'Um ataque físico simples, colidindo com o oponente.'),
('Fire Fang', 15, 95, 65, 'Fire', 'Morde o oponente com presas flamejantes, pode causar queimadura.'),
('Water Gun', 25, 100, 40, 'Water', 'Um jato de água fraco que atinge o oponente.'),
('Crunch', 15, 100, 80, 'Dark', 'Morde o alvo com força, podendo diminuir a defesa do oponente.'),
('Body Slam', 15, 100, 85, 'Normal', 'Um ataque corporal que pode paralisar o oponente.'),
('Thunder Punch', 15, 100, 75, 'Electric', 'Um soco eletrificado que pode paralisar o alvo.');

INSERT INTO Utilitarios (ID_item, Nome, Descrição, Preço, Consumivel)
VALUES
('U001', 'Potion', 'Restaura 20 HP de um Pokémon.', 20.00, TRUE),
('U002', 'Super Potion', 'Restaura 50 HP de um Pokémon.', 50.00, TRUE),
('U003', 'Hyper Potion', 'Restaura 200 HP de um Pokémon.', 150.00, TRUE),
('U004', 'Max Potion', 'Restaura todo o HP de um Pokémon.', 300.00, TRUE),
('U005', 'Full Restore', 'Restaura todo o HP e remove status de um Pokémon.', 400.00, TRUE),
('U006', 'Revive', 'Revive um Pokémon com metade do HP.', 200.00, TRUE),
('U007', 'Max Revive', 'Revive um Pokémon com todo o HP.', 500.00, TRUE),
('U008', 'Antidote', 'Cura o envenenamento de um Pokémon.', 10.00, TRUE),
('U009', 'Paralyze Heal', 'Cura a paralisia de um Pokémon.', 15.00, TRUE),
('U010', 'Burn Heal', 'Cura a queimadura de um Pokémon.', 15.00, TRUE),
('U011', 'Ice Heal', 'Descongela um Pokémon congelado.', 15.00, TRUE),
('U012', 'Full Heal', 'Cura qualquer condição de status de um Pokémon.', 40.00, TRUE),
('U013', 'Escape Rope', 'Permite escapar de uma caverna ou local fechado.', 55.00, FALSE),
('U014', 'Repel', 'Mantém Pokémon selvagens afastados por 100 passos.', 50.00, TRUE),
('U015', 'Super Repel', 'Mantém Pokémon selvagens afastados por 200 passos.', 100.00, TRUE),
('U016', 'Max Repel', 'Mantém Pokémon selvagens afastados por 250 passos.', 150.00, TRUE),
('U017', 'Pokeball', 'Usada para capturar Pokémon.', 20.00, TRUE),
('U018', 'Great Ball', 'Uma Pokébola com uma maior taxa de captura.', 50.00, TRUE),
('U019', 'Ultra Ball', 'Uma Pokébola com uma taxa de captura ainda maior.', 100.00, TRUE),
('U020', 'Master Ball', 'Garante a captura de qualquer Pokémon.', 1000.00, TRUE),
('U021', 'Rare Candy', 'Aumenta o nível de um Pokémon em 1.', 300.00, TRUE),
('U022', 'PP Up', 'Aumenta o PP máximo de um movimento de Pokémon.', 200.00, TRUE),
('U023', 'PP Max', 'Maximiza o PP de um movimento de Pokémon.', 500.00, TRUE),
('U024', 'Oran Berry', 'Restaura 10 HP de um Pokémon durante a batalha.', 10.00, TRUE),
('U025', 'Sitrus Berry', 'Restaura 25% do HP de um Pokémon durante a batalha.', 30.00, TRUE),
('U026', 'Leftovers', 'Recupera uma pequena quantidade de HP a cada turno.', 100.00, FALSE),
('U027', 'Focus Sash', 'Previne que o Pokémon seja nocauteado com um golpe.', 200.00, FALSE),
('U028', 'Choice Band', 'Aumenta o poder de ataque, mas limita a um movimento.', 300.00, FALSE),
('U029', 'Life Orb', 'Aumenta o poder de ataque ao custo de HP.', 250.00, FALSE),
('U030', 'Amulet Coin', 'Dobra o dinheiro ganho em batalhas quando o Pokémon que segura participa.', 150.00, FALSE);

INSERT INTO Treinadores (Nome, ID_treinador, Idade, Pokemon1, Pokemon2, Pokemon3, Pokemon4, Pokemon5, Pokemon6, Insignias)
VALUES 
('Lucas Silva', 'T001', 25, 'Spark', 'Fluffy', 'Tornado', 'Rocky', NULL, NULL, 4),
('Mariana Costa', 'T002', 18, 'Blitz', 'Shadow', 'Leafy', 'Storm', 'Magma', NULL, 3),
('Paulo Santos', 'T003', 30, 'Flash', 'Aqua', 'Echo', NULL, NULL, NULL, 6),
('Ana Pereira', 'T004', 22, 'Thunder', 'Blossom', 'Inferno', 'Gemini', NULL, NULL, 5),
('Ricardo Gomes', 'T005', 27, 'Crusher', 'Blaze', 'Frost', 'Luna', 'Beast', NULL, 2),
('Camila Rodrigues', 'T006', 19, 'Tempest', 'Pyro', 'Swift', NULL, NULL, NULL, 3),
('João Almeida', 'T007', 21, 'Boulder', 'Splash', 'Cinder', 'Venom', NULL, NULL, 5),
('Carla Fernandes', 'T008', 23, 'Windy', 'Flare', 'Spike', 'Glare', NULL, NULL, 4),
('Pedro Lima', 'T009', 28, 'Bolt', 'Rage', 'Frostbite', 'Vortex', 'Ivy', 'Steel', 3),
('Gabriela Souza', 'T010', 26, 'Whiskers', 'Inferno', 'Rocky', NULL, NULL, NULL, 6),
('Fernando Silva', 'T011', 24, 'Zephyr', 'Hurricane', 'Claw', 'Bramble', NULL, NULL, 5),
('Julia Mendes', 'T012', 20, 'Fluffy', 'Snappy', 'Fang', 'Blizzard', NULL, NULL, 4),
('Thiago Costa', 'T013', 29, 'Ember', 'Stormy', 'Hydra', NULL, NULL, NULL, 4),
('Isabela Oliveira', 'T014', 17, 'Sunny', 'Slash', 'Wisp', 'Flame', NULL, NULL, 2),
('Felipe Duarte', 'T015', 22, 'Drake', 'Talon', 'Ghost', 'Razor', 'Shimmer', NULL, 6),
('Beatriz Santos', 'T016', 18, 'Spikey', 'Thunder', 'Lava', NULL, NULL, NULL, 5),
('Guilherme Nunes', 'T017', 31, 'Claw', 'Boulder', 'Twister', NULL, NULL, NULL, 4),
('Patricia Borges', 'T018', 27, 'Mystic', 'Blade', 'Frost', 'Spark', NULL, NULL, 5),
('Carlos Rocha', 'T019', 35, 'Echo', 'Tornado', 'Spark', 'Flare', NULL, NULL, 3),
('Larissa Martins', 'T020', 19, 'Wings', 'Rocky', 'Thunder', 'Fury', NULL, NULL, 2),
('Rafael Ribeiro', 'T021', 23, 'Blitz', 'Cinder', 'Shadow', 'Fury', 'Scorch', NULL, 6),
('Fernanda Silva', 'T022', 21, 'Storm', 'Echo', 'Flare', NULL, NULL, NULL, 3),
('Vinicius Souza', 'T023', 26, 'Ice', 'Steel', 'Bolt', NULL, NULL, NULL, 5),
('Renata Melo', 'T024', 24, 'Rogue', 'Splash', 'Flame', 'Windy', NULL, NULL, 4),
('Roberto Ferreira', 'T025', 32, 'Blizzard', 'Crusher', 'Shadow', NULL, NULL, NULL, 3),
('Luana Barbosa', 'T026', 20, 'Scorch', 'Spike', 'Breeze', 'Volt', NULL, NULL, 4),
('Diego Costa', 'T027', 28, 'Talon', 'Inferno', 'Vortex', 'Spark', 'Boulder', 'Zephyr', 5),
('Alice Moreira', 'T028', 22, 'Whiskers', 'Blaze', 'Hydra', NULL, NULL, NULL, 6),
('Bruno Lima', 'T029', 33, 'Thunder', 'Razor', 'Frostbite', 'Steel', NULL, NULL, 4),
('Marta Souza', 'T030', 27, 'Pyro', 'Stormy', 'Rocky', 'Flare', NULL, NULL, 3); 

